### ISSUE TITLE
Ask End User's contacts when chatbot is unable to reply and CSA is not present

### ISSUE THREAD

**Issue by PaulaMerle** [buerokratt/Buerokratt-Chatbot#1]
AS AN End User
I WANT TO leave my contact data
SO THAT I don't need to wait and can get my answer when CSA is present/back

AS A CSA
I WANT TO receive the End User's contact information for any unanswered chats
SO THAT I can answer the request when I'm back at work

### Acceptance Criteria

- [ ] GUI as part of Backoffice GUI to [configure working hours of CSAs](https://github.com/buerokratt/Buerokratt-Chatbot/issues/15)
- [x] #44
- [ ] This functionality is triggered when chatbot is unable to reply (does not recognize an intent) and when 1) [All CSAs are unavailable (not present)](https://github.com/buerokratt/Buerokratt-Chatbot/issues/64) 2) Outside service hours 3) When calculated time (#7) is equal or longer than 2 minutes or queue number is equal or bigger than 2.
- [x] Chatbot should inform End User that it is not able to answer the question and 1) ["Hetkel ei ole klienditeenindajal võimalik vastata" (no CSA is available)](https://github.com/buerokratt/Buerokratt-Chatbot/issues/64), 2) ["Asutuse tööaeg on lõppenud" (outside service hours)](https://github.com/buerokratt/Buerokratt-Chatbot/issues/15), 3) "Klienditeenindajad on hõivatud" (long waiting time)
- [x] In case contact asking is triggered because of 1) and 2), chatbot asks if End User wants to leave contact information so that End User could receive the answer later - yes/no possibility. Text "Kas soovite jätta enda kontaktandmed, et klienditeenindaja saaks ise ühendust võtta?" 
- (1) When End User chooses "no", then end chat with status 2 from buerokratt/Placeholder#32
- (2) When End User selects "yes", then Chatbot displays contact form and text area with title "Täpsusta siin oma küsimust", text area is not mandatory to be filled 
- System verifies entered e-mail and/or phone number
- After successful verification Chatbot forwards chat to CSA, under "vestlus" (specified 28.11.2023 in #374)
- End User receives confirmation text "Aitäh pöördumast, Teiega võetakse esimesel võimalusel ühendust"
- [x] In case contact asking is triggered by 3), 3 options should be available 1) Wait 2) Leave contact information and end chat 3) Leave and end chat
-  When option 1 is selected, then chat remains active and no further notifications are displayed
- When option 2 is selected, then use same solution as above (2)
- When option 3 is selected, then end the chat and use option (1) https://github.com/buerokratt/Placeholder/issues/32

#### GUI

- [ ] According to https://www.figma.com/proto/rILEM6rghNvTsEKJ1wyQBn/B%C3%BCrokratt?node-id=738%3A13607&starting-point-node-id=738%3A13342&scaling=scale-down&show-proto-sidebar=1
- [ ] Chat Widget can be configured to make a REST call to a predefined endpoint in case the previous REST call did not respond with an HTTP 200 response code, resulting with asking for End User's contact information
- [ ] POST request with parameters
- [ ] Validate phone on a generic level
- [ ] Validate email on a generic level
- [ ] Show appropriate errors in case they exist in back-end response
- [ ] Show OK with confirmation in case no errors in back-end response

####  DSL

**Ruuter**

- [ ] Before the End User is asked for confirmation to transfer the chat to CSA, an additional step is added to validate if there are any CSAs currently online according to
1. [rules defined regarding fallback in case of an automated chatbot is unable to answer](https://github.com/buerokratt/Buerokratt-Chatbot/issues/44)
2. [rules defined regarding fallback in case an estimated waiting time exceeds the predefined value (in seconds) of End Users waiting](https://github.com/buerokratt/Buerokratt-Chatbot/issues/44)
- [ ] Use #64 when validating if there are any CSA's available

**Nodejs**

- [ ] #65
- [ ] #66

---

- [ ] Optional fields `end_user_email` and `end_user_phone` are added to the `chat` table
- [ ] End User's contact data can be requested from `cs-get-messages-by-chat-id` endpoint with other chat data

**Comment by turnerrainer** [comment]
Blocked by
https://github.com/buerokratt/Placeholder/issues/7
https://github.com/buerokratt/Placeholder/issues/32

**Comment by turnerrainer** [comment]
https://github.com/buerokratt/Buerokratt-Chatbot/issues/48

**Comment by joonasroosalung** [comment]
1. Added end_user_email and end_user_phone to all current chat related templates/sqls/configs.
2. endUserEmail and endUserPhone can be retrieved from all endpoints which return one or more chats.

Missing chatId request
```
curl -X POST --location "http://localhost:9090/end-user-email-phone" \
    -H "Content-Type: application/json" \
    -d "{
          \"chatId\": \"\",
          \"endUserEmail\": \"\",
          \"endUserPhone\": \"\"
        }"
```

Missing chatId response
```
{
  "response": "Missing chatId in request body."
}
```

Correct request
```
curl -X POST --location "http://localhost:9090/end-user-email-phone" \
    -H "Content-Type: application/json" \
    -d "{
          \"chatId\": \"123\",
          \"endUserEmail\": \"example@example.com\",
          \"endUserPhone\": \"+1 404\"
        }"
```

Correct response
```
{
  "response": "Updated 123 with example@example.com and +1 404."
}
```

**Comment by sergeirudz** [comment]
PR: https://github.com/buerokratt/Chat-Widget/pull/18

**Comment by rasmusei** [comment]
BUG
1. Short summary: Tested when all CSAs were unavailable
2. Expected result: When all CSAs were unavailable, the End User should be notified about that and asks to leave contacts
3. Current result: When all CSAs were unavailable and bot didn't know the answer, it still provided the option to forward message to backoffice
4. How to reproduce the bug: set all CSAs as unavailable, start conversation in the chat widget and ask something that bot does not know
Pic or video: I have a recording, but it's too big to upload

**Comment by rasmusei** [comment]
@PaulaMerle how to solve the contact showing chats?

**Comment by PaulaMerle** [comment]
If possible, it should be checked if the last event before closing the chat from bot-side was contact information received and if yes, the chat should remain in unanswered page until CSA takes it over and closes with the status "replied in another channel". If contact information is asked by bot but not provided by End-User, chat should be moved directly to History after ending from bot-side (either by bot or End-User).

**Comment by 1AhmedYasser** [comment]
@rasmusei @PaulaMerle Added the functionality to the bot to check if the organization is available and if there is a csa to available, also added a new endpoint `cs-get-all-unavailable-ended-chats` for future development which fetches all the ended chats that was ended from the bot side because the organization was unavailable or there was no CSA's available or it was a national holiday.

**Comment by janinakimtrohlev** [comment]
BUG - right now if CSA is not available it asks contact information. But if I as End User put my contact information, it tells that it is saved. First Bug this chat goes to history and the second one it doesn´t show any contact information. '

Should be : 
1. If the client sends his contact information after the bot's suggestion, the conversation is terminated on the client's side (it is important that the conversation is not terminated when contacts are requested at the initiative of CSA)
2. The conversation moves to the back room and remains on the pending/inactive chats page, where the attendant can take the person's contact information and close the conversation with the status "responded to the contact provided by the customer".
6m

**Comment by 1AhmedYasser** [comment]
@janinakimtrohlev You are right , when the organization is not available and the user enters his contact information, there should be another section introduced to show all chats that have user contact information left, so that the csa can contact the user later on.

This is currently not implemented
@turnerrainer @PaulaMerle @rasmusei , Could you provide your insights on this

**Comment by PaulaMerle** [comment]
@1AhmedYasser it is currently sufficient if such conversation will remain in unanswered chats' tab. CSA can see that end-user has provided the contact information (event notification in chat-flow) and take e-mail or phone from chat detail-view on the right-side of the screen.

**Comment by 1AhmedYasser** [comment]
@PaulaMerle This will cause some confusion because currently, unanswered chats tab is for chats that have the status open and a csa can take it over or forward it to someone else, it will require a core change in the unanswered chats logic and will cause confusion of which chats are open and which chats have ended with contact information

**Comment by PaulaMerle** [comment]
@1AhmedYasser status is supposed to stay open until CSA has taken the chat over, replied in other channel provided by end-user and terminated the chat with status "replied via other channel" (No 7 described in here https://github.com/buerokratt/Buerokratt-Chatbot/issues/33). Does the complexity here come from the fact that the conversation ends on the end user-side and then chat would receive ended status automatically?

**Comment by 1AhmedYasser** [comment]
> @1AhmedYasser status is supposed to stay open until CSA has taken the chat over, replied in other channel provided by end-user and terminated the chat with status "replied via other channel" (No 7 described in here #33). Does the complexity here come from the fact that the conversation ends on the end user-side and then chat would receive ended status automatically?

Yes, lets consider the following scenario

1. Late in the night a user tries to contact Büerokratt and the bot says to him (Büerokratt is not available, please leave your contact details).
2. The User leaves his contact details and then leaves the page.
3. In the next day when Büerokratt is open, they will contact the user using the contact information he provided

So when the user provide his contact information and leaves then the chat is no longer active because the client already left. so keeping it in OPEN status makes no sense, because even if a csa takes it over, he/she will be chatting with no one, because the user already is not there

**Comment by janinakimtrohlev** [comment]
BUG - I put right now that Bürokratt (organization time ) will be closed in 15:00 (now is 14:45) and I tested to open widget and to forward chat to CSA and it tells me that it is unable, out of working time and I can leave my contact information. 
So If I put organization time works till 15:00, then if I want to forward chat to CSA it should be forwarded until 15:00. 


![Image](https://github.com/buerokratt/Buerokratt-Chatbot/assets/122867977/424a25c9-e9a4-4272-b171-c62dae6bb448)

**Comment by janinakimtrohlev** [comment]
BUG - As administrator I put right now that bürokratt is working from 12:00 (now is 11:48). And as End User It still forward if something to CSA. But it is out of working time. 
Should be: If bürokratt is set up to open at 12:00 , then it will not allow End User chat to forward to CSA, but should ask a contact information, because it is out of working time.

**Comment by janinakimtrohlev** [comment]
Tested and done

**Comment by janinakimtrohlev** [comment]
BUG right now If Chatbot is out of working time it asks contact information. But doesn´t ask question about what question does end user haver.
![image](https://github.com/buerokratt/Buerokratt-Chatbot/assets/122867977/0c2b3c80-e174-44ac-9fd1-dd643ab34323)
Should be Chatbot displays contact form and text area with title "Täpsusta siin oma küsimust", text area is not mandatory to be filled

**Comment by janinakimtrohlev** [comment]
BUG - In contact form  should be not only contact information from client, but there is no text area to put the question from End User.

Should be when Chatbot displays contact form and text area with title "Täpsusta siin oma küsimust", text area is not mandatory to be filled.

**Comment by janinakimtrohlev** [comment]
Tested and done

**Comment by janinakimtrohlev** [comment]
BUG .
When there is no available CSA and client wants to speak with CSA it tries to forward, but it should give contact form. 
So when there is no CSA available the bot should give End User contact form. But now it forward to CSA.

P.S. before it worked

**Comment by 1AhmedYasser** [comment]
> BUG . When there is no available CSA and client wants to speak with CSA it tries to forward, but it should give contact form. So when there is no CSA available the bot should give End User contact form. But now it forward to CSA.
> 
> P.S. before it worked

This should be fixed now from database side, apparently due to testing there have been 2 accounts in idle status and 1 online, this edge case need to be investigated in order to prevent it.

**The Edge Case that caused this**: if a CSA logs in and then turns him/her self active and then closes the tab or browser without logging out, he will remain online or idle until he/she logs in again

**Comment by turnerrainer** [comment]
Needs a generic solution. Will solve it via https://github.com/buerokratt/Buerokratt-Chatbot/issues/478

**Comment by turnerrainer** [comment]
> Needs a generic solution. Will solve it via #478

Marking this issue as `Done` based on the above.
