### ISSUE TITLE
Buerokratt Chatbot deployment on Riigipilv

### ISSUE THREAD

**Issue by turnerrainer** [buerokratt/Buerokratt-Chatbot#151]
AS A Devops
I WANT Bürokratt to be deployed on Riigipilv automatically after new code commits to `main` branch
SO THAT I wouldn't have to do manual work for it

### Acceptance Criteria

- [x] buerokratt/Buerokratt-Chatbot#152
- [x] buerokratt/NoOps#29
- [x] buerokratt/Buerokratt-Chatbot#155
- [x] Database queries updates are applied based on [updated Resql DSLs](https://github.com/buerokratt/Buerokratt-Chatbot/tree/main/DSL.Resql)
- [x] Changes on [DataMapper DSLs](https://github.com/buerokratt/Buerokratt-Chatbot/tree/main/DSL.DMapper) are applied
- [x] Chat sessions can be used via both End User's Chat Widget and Back-Office (chat + all other functionality), will be solved by https://github.com/buerokratt/Buerokratt-Chatbot/issues/170

**Comment by turnerrainer** [comment]
Blocked until Ruuter v1 and v2 are both up and running. Related to https://github.com/buerokratt/NoOps/issues/1 + potentially needs additional attention in GUI part.

**Comment by turnerrainer** [comment]
Close due to using TEST for MVP and PLAY for new developments. Both have their own issues.
