### ISSUE TITLE
Amend organization's working time settings in BYK admin module

### ISSUE THREAD

**Issue by PaulaMerle** [buerokratt/Buerokratt-Chatbot#185]
AS AN Administrator
I WANT TO be able to set or modify organization's working time
SO THAT after working hours chatbot will ask End Users contact information when Bürokratt is not able to reply itself

Functionality has been worked out during phase2 development according to task #15, but needs some amendments to be done:

### Acceptance Criteria

- [ ] Working time must be configurable for each day separately according to Figma: https://www.figma.com/file/JYnmhsKixyUSCSUXXfwTAA/B%C3%BCrokratt?type=design&node-id=2371-16670&t=SvrXK7VqEdLeT6rI-4
- [ ] opt-in/opt-out for weekends, Figma: https://www.figma.com/file/JYnmhsKixyUSCSUXXfwTAA/B%C3%BCrokratt?type=design&node-id=2383-17594&t=SvrXK7VqEdLeT6rI-4
- [ ] simplified time schedule for workdays, Figma: https://www.figma.com/file/JYnmhsKixyUSCSUXXfwTAA/B%C3%BCrokratt?type=design&node-id=2383-17907&t=SvrXK7VqEdLeT6rI-4
- [ ] option for whole day closed, Figma: https://www.figma.com/file/JYnmhsKixyUSCSUXXfwTAA/B%C3%BCrokratt?type=design&node-id=2383-18174&t=SvrXK7VqEdLeT6rI-4

#### DSL

- [ ] #351
- [ ] #352

### GUI

- [ ] Apply GUI changes based on Figma design to BYK Admin (MVP)
- [ ] #350

**Comment by 1AhmedYasser** [comment]
@PaulaMerle @turnerrainer The requested design here is a new design and its currently needs changes to be done in the database and back-end side to achieve it and will require changes in BYK-Admin (MVP) as well in Chatbot (New Back-office)

### **This is the current design for it in Chatbot**
<img width="1728" alt="Screenshot 2023-11-07 at 2 29 58 AM" src="https://github.com/buerokratt/Buerokratt-Chatbot/assets/26207361/f8e931d9-9ad8-4042-b032-353d68883ade">

### **This is the new requested design**
<img width="911" alt="Screenshot 2023-11-07 at 2 30 34 AM" src="https://github.com/buerokratt/Buerokratt-Chatbot/assets/26207361/42ae6ede-870a-446c-94d7-4885b3504f16">

Would you like to change to the new design or keep the old one ?

**Comment by 1AhmedYasser** [comment]
@turnerrainer Currently when you check if the organization is within working hours, it will check if your `current time (UTC)` is between the `start time (UTC)` and `end time (UTC)` for the current day.

For example here is the Postgress query part that does that for example for `thursday`

```
WHEN current_day.current_day = 'thursday' THEN TO_CHAR(CURRENT_TIMESTAMP, 'HH24:MI:SS') BETWEEN
                                                     (SELECT TO_CHAR(value, 'HH24:MI:SS')
                                                      FROM thursday_start_time) AND
                                                     (SELECT TO_CHAR(value, 'HH24:MI:SS')
                                                      FROM thursday_end_time)
```

There is an edge case 

So for example if the current time is 22:00 (10:00 PM) and start time is 21:00 (09:00 PM) & end time is 01:00 (01:00) then it will fail, because 22:00 is not less than 01:00 because `01:00` is a new day time to the data base

But for example if you set the start time from 9:00 AM and end time is (17:00) (05:00 PM), and your current time is for example (13:00) (01:00) then it works fine

So the question here, how can we handle this edge case ?

**Comment by janinakimtrohlev** [comment]
Tested and done

**Comment by ValterAro** [comment]
The functionality is currently not working. Mentioned the bug in #682
