### ISSUE TITLE
Notifications to CSA's email that is connected to Bürokratt account

### ISSUE THREAD

**Issue by rasmusei** [buerokratt/Buerokratt-Chatbot#25]
AS A CSA
I WANT TO get notifications to my email
SO THAT I know about new unanswered incoming chats, when I'm away from computer

### Acceptance Criteria

> Rules covering sending email notifications are described [here](https://github.com/buerokratt/Buerokratt-Chatbot/issues/27) and are applied on all business-level ACs

- [ ] On/off functionalities, resolved within #27
- [ ] Send notification to email when there are new unanswered chats from Bürokratt that have no CSA's assigned
- [ ] Send notification to email when other CSA forwards chat by using #67

#### GUI
- [ ] According to [Figma designs (see on the right)](https://www.figma.com/proto/rILEM6rghNvTsEKJ1wyQBn/B%C3%BCrokratt?node-id=142%3A11049&starting-point-node-id=1%3A2&scaling=contain)
- [ ] POST request to an appropriate endpoint

#### DSL

**Send notification to email when there are new unanswered chats from Bürokratt that have no CSA's assigned**

- [ ] Add an additional step to an existing Ruuter v1 DSL `init-chat` to always make a request to a new Ruuter v2 endpoint `notification/csa/email`
- [ ] Send an appropriate email to all CSAs with preferences to accept email notifications about new chats
- [ ] Email is sent by making an appropriate REST call via #67

**Send notification to email when other CSA forwards chat**

- [ ] Add an additional step to an existing Ruuter v1 DSL `cs-redirect-chat` to send an email via #67

**Comment by joonasroosalung** [comment]
@turnerrainer Isn't this blocked by #67 - currently not in Ready status?

**Comment by ceirowe** [comment]
@rasmusei Resolved in #27

**Comment by joonasroosalung** [comment]
Currently left on new datamapper mock js mailer - {datamapper_url}/js/email/sendMockEmail. datamapper_url will have to be filled in on the *.urls.docker.json files.

For example I added the following to my all encompassing compose file:
```
  datamapper-node:
    container_name: datamapper-node
    build:
      context: ./DataMapper
    ports:
      - "3005:3100"
    networks:
      - bykstack
```

Therefore to the urls file I added `"datamapper_url": "https://datamapper-node:3005",`. The new endpoint will be used inside new steps in `init-chat` and `cs-redirect-chat` configs.

```
curl -X POST --location "https://localhost:8080/init-chat" \
    -H "Content-Type: application/json" \
    -d "{
          \"message\": {
            \"content\": \"124\",
            \"authorTimestamp\": \"2023-02-01T10:00:00.000Z\",
            \"authorRole\": \"end-user\"
          },
          \"endUserTechnicalData\": {
            \"endUserUrl\": \"https://localhost:3000/\",
            \"endUserOs\": \"Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:109.0) Gecko/20100101 Firefox/109.0\"
          }
        }"
```

```
curl -X POST --location "https://localhost:8445/cs-redirect-chat" \
    -H "Content-Type: application/json" \
    -d "{
          \"id\": \"s0me-ch4t-1d\",
          \"customerSupportId\": \"csa-1\",
          \"customerSupportDisplayName\": \"backend-user\",
          \"csaTitle\": \"\",
          \"forwardedByUser\": \"admin\",
          \"forwardedFromCsa\": \"csa-1\",
          \"forwardedToCsa\": \"csa-2\"
        }"
```

**Comment by joonasroosalung** [comment]
In order to start a new chat while the new DataMapper component is still in development, you can either remove the `post_customer_support_agent_notification` step from `init-chat` config, or add [DataMapper](https://github.com/buerokratt/DataMapper) to compose yml file. If DataMapper is added, datamapper_url (as opposed to dmapper_url), must be filled out in *.urls.docker.json files.

**Comment by janinakimtrohlev** [comment]
The mail server does not exist now.

**Comment by rasmusei** [comment]
@turnerrainer please take care of it and talk with Imre

**Comment by turnerrainer** [comment]
@rasmusei A quick summary is as following:

1. If we want our clients to get email notifications from `buerokratt@client.ee`, our clients need to configure their email settings in Bürokratt Backoffice by using their actual email server credentials;
2. If we want our clients to get email notifications from `client@buerokratt.ee`, we would have to create a central service to send these notifications. I don't think that would be a good a idea, as all `*@buerokratt.ee` emails might easily get blocked by spam filters.

**Comment by PaulaMerle** [comment]
Lets have option 1
