### ISSUE TITLE
Chatbot Module 2.0

### ISSUE THREAD

**Issue by rasmusei** [buerokratt/Buerokratt-Chatbot#257]
Acceptance Criteria

- [ ] Business requirements described
- [ ] Technical requirements described
- [ ] OpenAPI specifications created
- [ ] Resources acquired
- [ ] PLAY provides a near real-time overview of the current state of developments
- [ ] New features developed
- [ ] Finished developments deployed to TEST for automated testing
- [ ] Finished developments deployed to TEST for functional and behavioral testing
- [ ] Apply penetration testing for approved developments in TEST
- [ ] Deploy changes to PROD
- [ ] Procurement completed
