### ISSUE TITLE
Remake of SSE-based conversation flow

### ISSUE THREAD

**Issue by turnerrainer** [buerokratt/Buerokratt-Chatbot#358]
AS AN Architect
I WANT TO remake all SSE-based conversation flows in both MVP and version 2 of Bürokratt
SO THAT they would be technically on a more sustainable platform

### Acceptance Criteria

- [ ] Only send new messages once from the back-end
- [ ] GUI only fetches new chat data if it definitely exists
- [ ] Avoid making unnecessary requests to and within back-end systems
- [ ] Re-make post message preview (user typing) of Chat Widget and Backoffice v2

#### Scope of work

- [ ] [Chat Widget MVP](https://github.com/baha-a/byk-widget-mvp)
- [ ] [Backoffice MVP](https://github.com/baha-a/byk-customer-service-mvp)
- [ ] [Chat Widget v2](https://github.com/buerokratt/Chat-Widget)
- [ ] [Backoffice v2](https://github.com/buerokratt/Buerokratt-Chatbot)

#### GUI

- [ ] Keep an SSE stream open only to fetch notifications about updates from Nginx
- [ ] Upon new updates from Nginx, call the appropriate endpoint

#### DSL

- [x] #363
- [ ] #372

#### Nginx

- [ ] #362

**Comment by rasmusei** [comment]
Blocked by MVP widget and backoffice

**Comment by 1AhmedYasser** [comment]
Blocked Waiting for SSE Logic test on dev environment so it will be added in MVP widget and backoffice

**Comment by rasmusei** [comment]
Not blocked anymore

**Comment by 1AhmedYasser** [comment]
Remaining Adding SSE Logic to MVP widget and backoffice

**Comment by turnerrainer** [comment]
MVP needs more attention, moving back to "Ready".

1. To check notification layer proxy with @varmoh;
2. To check MVP endpoints and flow;
3. To check user authentication.

**Comment by turnerrainer** [comment]
Widget fixed according to @1AhmedYasser , continuing with the Backoffice.
