### ISSUE TITLE
Apply Nginx as a caching proxy to serve SSE requests

### ISSUE THREAD

**Issue by turnerrainer** [buerokratt/Buerokratt-Chatbot#362]
AS AN Architect
I WANT Nginx to be applied as a caching proxy to serve SSE requests
SO THAT the workload of other back-end components would be minimal

### Acceptance Criteria

- [ ] Set up Nginx with SSE compatibility
> Regarding AC below, see https://github.com/buerokratt/DMR for reference
- [ ] Configure Nginx to make requests to OpenSearch to get updates based on a specific `chat ID`
- [ ] Configure Nginx to make requests to OpenSearch to get updates on active chat list

#### GUI

- [x] #371

#### DSL

- `[GET]` `has-new-messages`
- `[GET]` `is-user-typing`
- `[GET]` `is-chat-list-updated`

**Comment by 1AhmedYasser** [comment]
Currently Using Node server
