### ISSUE TITLE
Apply fixed conversation flow mode to Chat Widget

### ISSUE THREAD

**Issue by turnerrainer** [buerokratt/Buerokratt-Chatbot#422]
> This is an enhancement based on https://github.com/buerokratt/byk-widget-mvp/issues/11
> Reference pull requests - https://github.com/buerokratt/byk-widget-mvp/pull/12, https://github.com/buerokratt/byk-widget-mvp/pull/13, https://github.com/buerokratt/byk-widget-mvp/pull/14
> The scope of this issue is Bürokratt v2, not MVP

AS A Product Owner
I WANT Chatbot conversations to be both text- and fixed conversation flow-based
SO THAT I could apply them both according to what's most suitable in given situation

### Acceptance Criteria

- [ ] Conversations can be either text- or fixed conversation flow-based depending on how they have been defined in the back-end (Rasa + Ruuter DSLs)

#### CSA

- [ ] CSA can create fixed conversation flows
- [ ] CSA can add optional selections for End User to choose from

#### End user

- [ ] Chat Widget displays optional selections for End User to choose from
- [ ] End User can press on the button of choice
- [ ] When in fixed conversation flow mode, the End User can not send any text

#### DSL

- [ ] Fixed conversation flows must be based on https://github.com/buerokratt/byk-widget-mvp/issues/11 schemas
- [ ] REST service to create a new fixed conversation flow
- [ ] REST service to apply changes in fixed conversation flow
- [ ] REST service to remove fixed conversation flow

#### GUI

- [ ] Apply buttons based on JSON input from the backend
- [ ] Button values must be translatable `i18n` values
- [ ] Technical solution based on https://github.com/buerokratt/byk-widget-mvp/issues/11

**Comment by 1AhmedYasser** [comment]
https://github.com/buerokratt/Buerokratt-Chatbot/issues/424 & https://github.com/buerokratt/byk-widget-mvp/issues/11 is done

remaining https://github.com/buerokratt/Training-Module/issues/353 & https://github.com/buerokratt/Training-Module/issues/354
