### ISSUE TITLE
Refactor critical Resql queries

### ISSUE THREAD

**Issue by turnerrainer** [buerokratt/Buerokratt-Chatbot#483]
AS AN Architect
I WANT some of Bürokratt's current critical Resql queries to be refactored
SO THAT they wouldn't crash the system

### Acceptance Criteria

- [ ] ~No `JOIN` queries can be used in SQL queries~
- [ ] No `UPDATE` queries can be used in SQL queries
- [ ] No `DELETE` queries can be used in SQL queries
- [ ] ~Only `INSERT` and `SELECT` queries can be used in SQL queries~
- [ ] ~Only [`denormalized databases`](https://en.wikipedia.org/wiki/Denormalization) can be used~
- [ ] Must specify requested selectors, `SELECT * ` is not allowed
- [ ] ~Every request must contain `LIMIT from, to` when listing results~
- [ ] Reduce `JOIN` queries to minimum
- [ ] Database schema changes are out of scope of this issue

##### Chatbot

- [ ] buerokratt/Buerokratt-Chatbot#564
- [ ] buerokratt/Buerokratt-Chatbot#565
- [ ] buerokratt/Buerokratt-Chatbot#566
- [ ] buerokratt/Buerokratt-Chatbot#567
- [ ] buerokratt/Buerokratt-Chatbot#583
- [ ] buerokratt/Buerokratt-Chatbot#584
- [ ] buerokratt/Buerokratt-Chatbot#585

##### Analytics Module

- [ ] buerokratt/Analytics-Module#213
- [ ] buerokratt/Analytics-Module#214
- [ ] buerokratt/Analytics-Module#222
- [ ] buerokratt/Analytics-Module#223
- [ ] buerokratt/Analytics-Module#224

#### Training Module

- [ ] buerokratt/Training-Module#486
- [ ] buerokratt/Training-Module#487
- [ ] buerokratt/Training-Module#488

#### Service Module
- [ ] buerokratt/Service-Module#276
- [ ] buerokratt/Service-Module#277
- [ ] buerokratt/Service-Module#278

**Comment by 1AhmedYasser** [comment]
@turnerrainer @baha-a 

#### Most Critical Queries:

#### Chatbot Module
1. `get-cs-all-active-chats.sql`
2. `get-cs-all-ended-chats.sql`
3. `get-cs-all-pending-chats.sql`
4. `get-cs-all-unavailable-ended-chats.sql`

#### Analytics Module
1. `csa-chat-forwards.sql`
2. `feedback-chats-with-negative-feedback.sql`

Notes:

1. Check for any `select *` and refactor it to use `select {field_name}`
2. Service Module have some queries that uses update and delete, we need to make sure only insert and select are used
