### ISSUE TITLE
Software versioning

### ISSUE THREAD

**Issue by turnerrainer** [buerokratt/Buerokratt-Chatbot#561]
AS AN Architect
I WANT only versioned code to be used in `stage` environment
SO THAT the content published would be previously verified

> The scope of this issue is limited to once-only setup, which will then be taken over step-by-step as a normal processes of development

### Acceptance Criteria

- [ ] Use [`git tags`](https://git-scm.com/book/en/v2/Git-Basics-Tagging) for versioning
- [ ] Only `stage` branch, only commits with version numbers are allowed
- [ ] On `stage` branch, all commits must contain `-rc` suffix to represent them as _release candidates_
- [ ] Provide release notes with cross-reference to related versions of Components and Modules
- [ ] Code can only be moved from one branch (environment) to another by using pull requests
- [ ] Pipelines will only be triggered when pushing to branches (environments), using changes on `.env` files as triggers
> See https://github.com/buerokratt/Buerokratt-Chatbot/blob/dev/.env as an example
- [ ] buerokratt/NoOps#152 as the scope of the issue

#### Versioning concept

- [ ] In `dev`, only hashes are used - _no versioning_
- [ ] In general, based on the concept of [Semantic Versioning 2.0.0](https://semver.org/)

> _Given a version number MAJOR.MINOR.PATCH, increment the:_
> _`MAJOR` version when you make incompatible API changes_
> _`MINOR` version when you add functionality in a backward compatible manner_
> _`PATCH` version when you make backward compatible bug fixes_
> _Additional labels for pre-release and build metadata are available as extensions to the MAJOR.MINOR.PATCH format._

- [ ] Version numbers consist of `MINOR`.`MAJOR`.`PATCH`
- [ ] All version numbers start with `v` as _"version"_

> Based on an assumption that the end result will be `v2.3.0`

#### Dev environment

> Active development takes place here
> No versioning is done here

- [ ] Based on `dev` branch

#### Test environment

> QA takes place here
> Alpha releases for incomplete features

- [ ] Code committed to `test` branch
- [ ] Based on `test` branch's latest commit
- [ ] Beta release versioned as `v2.3.0-alpha.1`
> If needed
- [ ] Beta release versioned as `v2.3.0-alpha.2`
- [ ] Beta release versioned as `v2.3.0-alpha.3`
- [ ] Beta release versioned as `v2.3.0-alpha.4`

> Beta releases for features that are _expected_ to be completed, but need to be tested

- [ ] Based on `test` branch's latest `alpha`-versioned commit
- [ ] Beta release versioned as `v2.3.0-beta.1`
> If needed
- [ ] Beta release versioned as `v2.3.0-beta.2`
- [ ] Beta release versioned as `v2.3.0-beta.3`
- [ ] Beta release versioned as `v2.3.0-beta.4`

#### Stage environment

> Expected to be fully functional and tested
> Penetration testing takes place here if needed
> Final testing before publishing as the latest stable version in `main` takes place here

- [ ] Based on `test` branch's latest `beta`-versioned commit
- [ ] Code committed to `stage` branch
- [ ] Relase candidates versioned as `v2.3.0-rc.1`
> If needed
- [ ] Relase candidates versioned as `v2.3.0-rc.2`
- [ ] Relase candidates versioned as `v2.3.0-rc.3`
- [ ] Relase candidates versioned as `v2.3.0-rc.4`

#### Production environment

- [ ] Based on `stage` branch's latest `rc`-versioned commit
- [ ] Code committed to `main` branch
- [ ] Version `v2.3.0`
> If needed
- [ ] Version `v2.3.1`
- [ ] Version `v2.3.2`
- [ ] Version `v2.3.3`
