### ISSUE TITLE
Modifications in the GUI for version 2.0

### ISSUE THREAD

**Issue by rasmusei** [buerokratt/Buerokratt-Chatbot#633]
AS A Product Owner
I WANT to modify Bürokratt 2.0 version GUI 
SO THAT not ready or not working functionalities won't available for the Users
AND currently writen descriptions would make more sense to the Users
AND to make sure that everything is in Estonian and visibly better to use

### Acceptance Criteria

- [x] buerokratt/Buerokratt-Chatbot#637
- [x] buerokratt/Buerokratt-Chatbot#636
- [x] buerokratt/Training-Module#510
- [x] buerokratt/Buerokratt-Chatbot#639
- [x] buerokratt/Buerokratt-Chatbot#640
- [x] buerokratt/Buerokratt-Chatbot#641
- [x] buerokratt/Buerokratt-Chatbot#642
- [x] buerokratt/Buerokratt-Chatbot#643
